apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5VENDQWQyZ0F3SUJBZ0lSQUlmWGo3NVYwa2dYbDdkRHdOd2lRUGN3RFFZSktvWklodmNOQVFFTEJRQXcKSWpFZ01CNEdBMVVFQXd3WGEzVmlaWEp1WlhSbGN5MWpiSFZ6ZEdWeUxUa3pOall3SGhjTk1qUXdOVEkxTVRBegpOVEl6V2hjTk1qa3dOVEkxTVRBek5USXpXakFpTVNBd0hnWURWUVFEREJkcmRXSmxjbTVsZEdWekxXTnNkWE4wClpYSXRPVE0yTmpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGFCTS9XYzVhQTQKbkJJVzM2ZXJZV0hqY1Vtd0psSHcweDNaZVZkaEJ1bHB0TVhQdUlaS2xYc2o2aXlQTE9MaitITUphK2kwNDZZSgp6Vy9JdkdhUWt4L2JmbmJBRUQ1Nm4xNnN3TDh2bmNJMXhndFBTM3ZYb1FqVitTZG1vK3JyMUFQM1NlN0FBeDNBCjRCeGZaTkRJTnJSaCs3Um9GRGl1TUprd3ZBYnpnbW84VmFFNEdWMkI3emErRE5XblBSeVZwK1BhR2hDVnl6bGYKZ2RCUldPR09BWjZkUm15R0cvTWxyNzVxVUtXZVN2enhmSitsamc2NGhTWk1XVkY4K3VVY3lLV05qQ2plaktTZQp6azQ3VDZzM1pTRk5VK0FsZGZRRzdBWkZ4VlRncDdVcWI5VC9YRlBTWVRUQzFuTWszU3lIZ1B2WlpJQXVWVzJjClkxY1dickFHYkMwQ0F3RUFBYU1tTUNRd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFEQU9CZ05WSFE4QkFmOEUKQkFNQ0FnUXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQnZ0ZUpQbTZxcU4veGxSVlcrV29GVXVLV2hGS1hCeApHbU5WK25kVXZydDRERmR3RGxpY1FyRGEzS2N1VkR5Y0pNbmkxU2hlS0RIV3BydmIxWWpVUVFqbE41K2dhTkFNCmE1UmFjYW1qU3RlOGRIVm50MXdscFdDcWs3b0hnNmd2YTJwUkE3amdsUUQ2eU5vQ01Ya01CQ0NwL3pHd0JrYzMKVkVYUSt0cytrZ3cyK2lyY05XeWxwTjBVaXZlcmV6TDFxbmFvcVllZWFDeitOa2IyTXNZcThHMlE4L3o5WVl6VgpNVStiNDhqR0dzelhJR0phbWEvWDBaekNBNHJNeTljRVBZanYvT2x2SlFyRmptdlFCMjVBaU1Wck43NGFnT2t4CmlOUDZIdkYvS01jdHZ5dEtnc0lkVHZXaDRMcWVKanJJMmtYSUd6Y3k5ZzZkbW9lVEUwTEJXdDQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://90.156.218.238:6443
    name: kubernetes-cluster-9366
contexts:
  - context:
      cluster: kubernetes-cluster-9366
      user: kubernetes-cluster-9366
    name: default/kubernetes-cluster-9366
current-context: default/kubernetes-cluster-9366
kind: Config
preferences: {}
users:
  - name: kubernetes-cluster-9366
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args: null
        command: client-keystone-auth
        env:
          - name: "OS_AUTH_URL"
            value: "https://infra.mail.ru:35357/v3/"
          - name: "OS_USERNAME"
            value: "alesur@bk.ru"
          - name: "OS_PASSWORD"
            value: "LA7+ch@Tc"
          - name: "OS_PROJECT_ID"
            value: "014b3358157a44c5928296cd9674fbd4"
          - name: "OS_DOMAIN_NAME"
            value: "users"
        interactiveMode: IfAvailable
        provideClusterInfo: false