apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5VENDQWQyZ0F3SUJBZ0lSQUpZR0xwR3dQMHpvalQweWRYUzNheEV3RFFZSktvWklodmNOQVFFTEJRQXcKSWpFZ01CNEdBMVVFQXd3WGEzVmlaWEp1WlhSbGN5MWpiSFZ6ZEdWeUxUVTFPVGt3SGhjTk1qUXdOVEk0TVRreApOREk0V2hjTk1qa3dOVEk0TVRreE5ESTRXakFpTVNBd0hnWURWUVFEREJkcmRXSmxjbTVsZEdWekxXTnNkWE4wClpYSXROVFU1T1RDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSnpGbjZabURKcEYKOTBXK3FvMDgyMVAxQktBdmxidU1OMEdLMDQ4V256ZlBQZkVJb2h4bzZPcURUL3NzaUh5UWlOdkNoUERlaDA4RQp0aS9yNHEvT0hhYTV5c2R1RFkyczh0RHI0Sm8xN0tUMFY5b3VXR1BYcjlEVGlmYmlFM2hMZlc0eHlqVjN0MDFQClNFbGlxbUt0TUhaejNrMWNmT1NVNG1OUG85Wm1ZazVMc0dOOVRSNTB5cms5bnkyc2JTdHdjNmR2NTlHZnh1NG4KTlNDR0ExUlNtdkVlQTByTnlGWHp6TTFFQmtIR1RBQ3hyZEg5Y2VxYmZQbEVZdFlUN3lTUFNpWXVVSTJGVi9SeQp2SmxDVE4wUlpCckdZMUVhcnFEQVZQZEIwNzI4cUowTzZDU3FpbzBxODZmcGlxdkErQ29KOXpwSXVteWp4R3BICm41U1dJaW9TWGI4Q0F3RUFBYU1tTUNRd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFEQU9CZ05WSFE4QkFmOEUKQkFNQ0FnUXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSHZtNW5RMnVOY2tVcGx4QnoyeEU3N3dnM09kVkZKRQpKR0xOOENwa1ZQelJYRVpld2hUUlFHQ1VlM2pITERFM3p0K3lVMmxDVUd3NStqcVdsc3VuQUdhQk9kSDl0bzhHCmhBZlRrd0hxaTdXWkJLTlZObDRNRWFZM3UwNzRVSlE4b2FtclE3RDFwN1FwelRVM0NpR0J5RnVzSklZejZZeWsKNmJKdFBDSFg3VnZzMHEwcnRPT1c4S2NueHdIRHNSdlpsNndZYTgrenAzYUk2enlBRSszb2dUNkRMUXJiTUU5SgpUTktVa3NTZDMyeWJGenZ6R283RWdOS05sL3hiVjN1TVUwVThWZ0NiS2NPK3NNcFBMME5qeXNFQ3E4eGFLckF5Cm9kdC92SXpkdXN1dE10c204WXY5dStyZUNjaVczdEdyUm5rbnAxOGw2NjZwd0thMUt4Y0ZYYzQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://91.219.226.224:6443
    name: kubernetes-cluster-5599
contexts:
  - context:
      cluster: kubernetes-cluster-5599
      user: kubernetes-cluster-5599
    name: default/kubernetes-cluster-5599
current-context: default/kubernetes-cluster-5599
kind: Config
preferences: {}
users:
  - name: kubernetes-cluster-5599
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args: null
        command: client-keystone-auth
        env:
          - name: "OS_AUTH_URL"
            value: "https://infra.mail.ru:35357/v3/"
          - name: "OS_USERNAME"
            value: "alesur@bk.ru"
          - name: "OS_PASSWORD"
            value: "LA7+ch@Tc"
          - name: "OS_PROJECT_ID"
            value: "014b3358157a44c5928296cd9674fbd4"
          - name: "OS_DOMAIN_NAME"
            value: "users"
        interactiveMode: IfAvailable
        provideClusterInfo: false