apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5RENDQWR5Z0F3SUJBZ0lRRkJxaEVDd1ZSRytDVEZJeHVxYURKREFOQmdrcWhraUc5dzBCQVFzRkFEQWkKTVNBd0hnWURWUVFEREJkcmRXSmxjbTVsZEdWekxXTnNkWE4wWlhJdE9EVTNPREFlRncweU5EQTJNRE15TXpJMQpNekJhRncweU9UQTJNRE15TXpJMU16QmFNQ0l4SURBZUJnTlZCQU1NRjJ0MVltVnlibVYwWlhNdFkyeDFjM1JsCmNpMDROVGM0TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF4ZG1MazFoeUZCNlIKdGVjVjcvdGpCSjI4UWp6MnJTRTRCalovUk5TWlZZekdDWE4zWWQyc09xaURzZk9hL1lUaFJhY0Q3NWpEcEJhUQpadkI1SUhpV0lUanNBWlNBYzVocWVMQjVuY0d2a2lUSmIxb3V4SC91U0xkRFdnVVZOSGlWN1N3a3R1ZEhiWWwrCnNFMitnTW80VWFtVnlpSVRTUmZnK1FRUnZHQzdib0w4TWhHa2RiL3BnaEU4MUdXeUw5MitCMFllMlFMWThvbmUKTnFtUHN4a1pzb3ZiWU5VbDhqdmxMWHFwWmhWUDZES2QreEFSUkNFUXBlKzdZbVhJdk5OQ242eFNHV0VhcnpWegpIOXF4dlNEU0l5Nm52Sy80SUQxOE40NGRDZ3lhdm1JS3d4SzhrNm5ycmtEaTRaVFNuM0g3T2hEU3RVSTBWenJLCmt3bDVwaUVnSFFJREFRQUJveVl3SkRBU0JnTlZIUk1CQWY4RUNEQUdBUUgvQWdFQU1BNEdBMVVkRHdFQi93UUUKQXdJQ0JEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFRcG9PZ3lMc3lBaUJ6ZjcvOSt3VENIWDRBeFBOS3JJUAp2eENjZW4zVkIwc3RvZG5SRG00WEdpMDZibnJ1TlhvdW1ZM0s4dHhJREQxaktFTXVsRTRueVB0eUZQaWQ5WHR2CkE1OHBUREYzTlpSZzlFNjhaclhZM2tLV2RJeU9ib0c1M21BNFdEOVRDV0xWQjhuVlgzNGFUSHBOek5nZHZFZ1oKQTlGMzJ1bEUybCtGRUN1OGtibGd5R2NUZExEOEdGOHJRbnNIbkQ4eDZrcC9qYTY0SjY1S3BUS2JsdTNEQ2xHYwoxNUhXNEltdzUrdThRL1NWNExYY3ZhbmtBYkZRV0J4UTNhT3J3YVNVMmRQZGVOREh2cWsvdXNhWUIzNVovTmV3CmM3dm1mNVZCMUpoOTBKbnV4b2o2T1UzR1JRM1VMbjdJaC9xdFNCSUhHUnpxY1A0OVB6OUJwZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://91.219.226.224:6443
  name: kubernetes-cluster-8578
contexts:
- context:
    cluster: kubernetes-cluster-8578
    user: kubernetes-cluster-8578
  name: default/kubernetes-cluster-8578
current-context: default/kubernetes-cluster-8578
kind: Config
preferences: {}
users:
- name: kubernetes-cluster-8578
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: client-keystone-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://infra.mail.ru:35357/v3/"
      - name: "OS_USERNAME"
        value: "alesur@bk.ru"
      - name: "OS_PASSWORD"
        value: "LA7+ch@Tc"
      - name: "OS_PROJECT_ID"
        value: "014b3358157a44c5928296cd9674fbd4"
      - name: "OS_DOMAIN_NAME"
        value: "users"
      interactiveMode: IfAvailable
      provideClusterInfo: false